### PR TITLE
Updating the Help Links of all the components

### PR DESCRIPTION
**Pull request by aryanndwi123**
Fixes #206

#### Describe the changes you have made in this PR -
Updated all the Help Links in the required files (except the ones in which there is no docs regarding that page)

### Screenshots of the changes (If any) -

https://circuitverse.netlify.app/simulatorvue

When we click on the help button of any component then it redirect us to the PageNotFound Page (Because the links were not updated)

PageNotFound

But after changing the links to the correct ones it works !

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by aryanndwi123** [comment]
Hi @Prerna-0202 @Arnabdaz ,
Can you please review my PR and tell me any changes if needed.

**Review by Prerna-0202 — CHANGES_REQUESTED** [review]
Please change the link in Stepper.js, Splitter.js  and Demultiplexer.js also.

**Comment by aryanndwi123** [comment]
> Please change the link in Stepper.js, Splitter.js and Demultiplexer.js also.

Yes @Prerna-0202 , I made those changes!

**Review by Prerna-0202 — APPROVED** [review]
Great 🎉

**Review by Arnabdaz — APPROVED** [review]
cc @vedant-jain03 @tachyons

**Pull request merged**
