### PR TITLE
feat: updated issue and feature request template

### PR DESCRIPTION
**Pull request by pankaj-2503**
Fixes #

#### Describe the changes you have made in this PR -
Updated the issue and feature request template as in the main repo of CircuitVerse.
### Screenshots of the changes (If any) -
**After:**
image
image

Hence Solves the issue #253
Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by niladrix719** [comment]
@pankaj-2503 you can use yaml based templates like the main repo. ref pr: https://github.com/CircuitVerse/CircuitVerse/pull/3544

**Review by niladrix719 — COMMENTED** [review]
@pankaj-2503 you can use yaml based templates like the main repo. ref pr: https://github.com/CircuitVerse/CircuitVerse/pull/3544

**Comment by pankaj-2503** [comment]
> @pankaj-2503 you can use yaml based templates like the main repo. ref pr: [CircuitVerse/CircuitVerse#3544](https://github.com/CircuitVerse/CircuitVerse/pull/3544)

Yeah ,sure i thought it was written in .md so i hadn't changed the file to yml

**Comment by pankaj-2503** [comment]
> @pankaj-2503 you can use yaml based templates like the main repo. ref pr: [CircuitVerse/CircuitVerse#3544](https://github.com/CircuitVerse/CircuitVerse/pull/3544)

Hey , i have created updated pull request please review this https://github.com/CircuitVerse/cv-frontend-vue/pull/255

**Pull request closed without merging**
