### PR TITLE
feat(gsoc'24): Implemented LayoutElements Panel vue component

### PR DESCRIPTION
**Pull request by niladrix719**
Fixes [#108](https://github.com/CircuitVerse/upptime/issues/108)

#### Describe the changes you have made in this PR -

Created a Vue component out of LayoutElement Panel which was previously in the `extra.vue` file

- moved all DOM manipulation to vue's reactives
- moved all styles to scoped view

### Screenshots of the changes (If any) -

https://github.com/CircuitVerse/cv-frontend-vue/assets/91966855/baa644af-feb7-42ba-b4a6-f62f13568369

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `LayoutElementsPanel` component for improved management and display of layout elements.
	- Enhanced user interaction with a draggable panel and expandable groups for subcircuit elements.

- **Localization**
	- Added new translations for layout-related elements in Bengali, English, and Hindi, improving accessibility for users.

- **Bug Fixes**
	- Improved state management for subcircuit elements, ensuring accurate display and interaction within the user interface.

- **Style**
	- Removed outdated CSS class for the layout element panel, streamlining the styling process.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@niladrix719 can you check the failed tests?

**Review by vedant-jain03 — APPROVED** [review]

**Review by Arnabdaz — CHANGES_REQUESTED** [review]
fix the dropdown and icons not showing up 
you can take reference from the circuit element panel

**Comment by vedant-jain03** [comment]
@niladrix719 are you sure you take care of :

> fix the dropdown and icons not showing up
you can take reference from the circuit element panel

**Review by Arnabdaz — CHANGES_REQUESTED** [review]
- dropdown is not working 
image

- labels are getting removed when we drag the element in canvas in layout mode
  should be like below image:
image

**Review by Arnabdaz — APPROVED** [review]
Nice work :+1:

**Pull request merged**
