### PR TITLE
feat(drag): bug fixes for drag.ts

### LINKED ISSUE #194: Navbar hover dropdown is going behind Circuit Elements
**Describe the bug**
 Navbar hover dropdown is going behind Circuit Elements on mimimizing circuit elements and then maximizing it.

**To Reproduce**
1. Go to 'https://circuitverse.netlify.app/simulatorvue'
2. Minimize the Circuit elements using minus button
3. Again expand the Circuit Elements
4. Hover over the Project tab and notice that the dropdown is going behind, and not all options are visible even if you minimize the circuit element

**Expected behavior**
 The dropdown elements should come in front of Circuit Elements

**Screenshots**
Screenshot 2023-11-18 at 7 19 25 PM

https://github.com/CircuitVerse/cv-frontend-vue/assets/65560026/8a03e8c7-9dda-450e-9474-0e52bc22018c

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by aryanndwi123**
Fixes #194 

#### Describe the changes you have made in this PR -
-Changes in Drag.ts, changed the z-index.

### Screenshots of the changes (If any) -
Before changes: -

After changes: -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by aryanndwi123** [comment]
Hi @Prerna-0202 , 
Can you please review this pr and tell me changes. 
I'm new to the open-source !!!

**Comment by Prerna-0202** [comment]
Good work @aryanndwi123.  However, when we drag the timing diagram, properties panel, testbench panel, and quick-button panel, and then open any dropdown, the dropdown is still getting hidden. I think the dropdowns should be visible above all of these panels.

Could you make these changes also?

**Comment by aryanndwi123** [comment]
Yes @Prerna-0202 , I have done the changes what you have mentioned.
Adjusted z-index to ensure dropdowns appear above panels.

**Review by Prerna-0202 — APPROVED** [review]
Great 🎉

**Review by vedant-jain03 — APPROVED** [review]

**Pull request merged**
