### PR TITLE
Fix: Circuit Elements Panel Bug Hiding Lower Section

### LINKED ISSUE #285: [Bug: UI] Circuit Elements Panel: Expanded Elements Hide Lower Section
**Description:**
When expanding certain groups of elements in the Circuit Elements panel, the lower section of the panel gets hidden, making it inaccessible and causing usability issues.

**Steps to Reproduce:**
1. Go to [cv-frontend-vue](https://circuitverse.netlify.app/simulatorvue)
2. In the Circuit Elements panel, Expand any group of elements within it.
3. Observe that the lower section of the panel is hidden below the viewport.

**Expected Behavior:**
The entire Circuit Elements panel should remain visible and accessible after expanding any group of elements. No part of the panel should be hidden or inaccessible.

**Screenshots:**

https://github.com/CircuitVerse/cv-frontend-vue/assets/89861718/ebe987d8-5776-41d4-90ed-d4e0048ab7a8

Screenshot UI Bug

**Device Information:**
- OS: Windows 11
- Browser: Chrome
- Version: Chrome 122

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by itsHamdySalem**
Fixes #285 

#### Describe the changes you have made in this PR -
Adjusted the styling of the panel body in the `ElementsPanel` component to enable vertical scrolling. This ensures that the panel remains fully accessible even when expanded elements exceed the viewport height.

### Screenshots of the changes (If any) -
- before the changes:

https://github.com/CircuitVerse/cv-frontend-vue/assets/89861718/837ec6ce-52d4-40a2-96ef-b1517cd80793

- after the changes:

https://github.com/CircuitVerse/cv-frontend-vue/assets/89861718/ea26021b-8192-46a3-86af-6754b8f0c331

### CODE REVIEW

**Review by Arnabdaz — CHANGES_REQUESTED** [review]
this solution would make it confusing for users and also the user experience would degrade. 
I would suggest you to take a approach like the main simulator where we decreased the height of the sections you can see the [main simulator](https://circuitverse.org/simulator) for more info.

**Comment by itsHamdySalem** [comment]
> this solution would make it confusing for users and also the user experience would degrade. I would suggest you to take a approach like the main simulator where we decreased the height of the sections you can see the [main simulator](https://circuitverse.org/simulator) for more info.

Thank you for your feedback. I understand your concerns about the proposed solution potentially confusing users and degrading the user experience.

Regarding your suggestion to decrease the height of the sections, while it was implemented, it didn't fully resolve the issue. Expanding any section when the panel is moved down still poses a problem.

I propose an alternative solution: instead of hiding the scrollbar, we could style it to make it visible. This would maintain clarity for users while ensuring a smooth user experience.

I'd appreciate your input on which approach to proceed with.

Once again, I appreciate your thorough review and suggestions.

**Comment by Arnabdaz** [comment]
@itsHamdySalem I would recommend you going with the solution as in the current simulator we can brainstorm on some better solution later but let's not add scrolling into the panels for now.

**Comment by itsHamdySalem** [comment]
@Arnabdaz Thank you for your feedback. I've already proceeded with your suggestion and pushed the changes. Please check the deploy preview for verification.

**Review by Arnabdaz — APPROVED** [review]

**Comment by Arnabdaz** [comment]
nice work @itsHamdySalem 
you can join out slack channels for discussions about how to improve the panels

**Pull request merged**
