### PR TITLE
fix(typo): changes sate to state

### PR DESCRIPTION
**Pull request by Sarthaknegigit**
fix: Typo in line 9 of README.md

changes Sate to State

### CODE REVIEW

**Comment by Sarthaknegigit** [comment]
can someone please help me with the issue, the commit lint wont let me commit even when the commit is in accordance to the convention.

**Comment by vedant-jain03** [comment]
> can someone please help me with the issue, the commit lint wont let me commit even when the commit is in accordance to the convention.

Welcome to CircuitVerse 🎊 

It is because of the commit message, that follow [this](https://www.conventionalcommits.org/en/v1.0.0/) to make the commit message meaningful!

**Comment by Sarthaknegigit** [comment]
@vedant-jain03 Hey Vedant, Thank for the prior help.
Can you please resolve one more doubt of mine that whether I need to close this PR and write a new one or is their any mechanism where I can link the PR in this thread only?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 Hey Vedant, Thank for the prior help. Can you please resolve one more doubt of mine that whether I need to close this PR and write a new one or is their any mechanism where I can link the PR in this thread only?

You don't need to close or open a new PR. You can add the changes in the current PR branch, add, commit, and push them!

**Comment by Sarthaknegigit** [comment]
#16 Typo in README.md resolved. Please review.

**Comment by devartstar** [comment]
Thank you @Sarthaknegigit for the fix.

**Comment by Sarthaknegigit** [comment]
> Thank you @Sarthaknegigit for the fix.

Thank you for guiding me through my first PR.

**Pull request merged**
